name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/vector.png
    - assets/page-1/images/icon.png
    - assets/page-1/images/triangle.png
    - assets/page-1/images/base.png
    - assets/page-1/images/auto-group-t96d.png
    - assets/page-1/images/push.png
    - assets/page-1/images/path.png
    - assets/page-1/images/group-19.png
    - assets/page-1/images/icon-MBX.png
    - assets/page-1/images/path-3t5.png
    - assets/page-1/images/polygon-1.png
    - assets/page-1/images/rectangle-20.png
    - assets/page-1/images/icon-A81.png
    - assets/page-1/images/percent.png
    - assets/page-1/images/push-a8H.png
    - assets/page-1/images/arrow.png
    - assets/page-1/images/cycling-track.png
    - assets/page-1/images/avatar.png
    - assets/page-1/images/base-jmB.png
    - assets/page-1/images/auto-group-ahgy.png
    - assets/page-1/images/rectangle-35.png
    - assets/page-1/images/icon-7p5.png
    - assets/page-1/images/close.png
    - assets/page-1/images/arrow-pBB.png
    - assets/page-1/images/triangle-Jbs.png
    - assets/page-1/images/icon-zQZ.png
    - assets/page-1/images/vector-1kD.png
    - assets/page-1/images/rectangle-35-yQM.png
    - assets/page-1/images/ellipse-bg.png
    - assets/page-1/images/auto-group-94mb.png
    - assets/page-1/images/icon-nGH.png
    - assets/page-1/images/button.png
    - assets/page-1/images/ellipse-14.png
    - assets/page-1/images/rectangle-34.png
    - assets/page-1/images/auto-group-s7hf.png
    - assets/page-1/images/close-Wnd.png
    - assets/page-1/images/arrow-EYq.png
    - assets/page-1/images/vector-MtM.png
    - assets/page-1/images/auto-group-qrkz.png
    - assets/page-1/images/icon-Tkd.png
    - assets/page-1/images/icon-FNH.png
    - assets/page-1/images/vector-9Vb.png
    - assets/page-1/images/auto-group-w51o.png
    - assets/page-1/images/icon-bfw.png
    - assets/page-1/images/button-z9f.png
    - assets/page-1/images/ellipse-14-Ucq.png
    - assets/page-1/images/auto-group-2qdw.png
    - assets/page-1/images/base-ohb.png
    - assets/page-1/images/icon-wah.png
    - assets/page-1/images/auto-group-7pau.png
    - assets/page-1/images/tick-removebg-preview-7.png
    - assets/page-1/images/auto-group-myss.png
    - assets/page-1/images/tick-removebg-preview-6.png
    - assets/page-1/images/tick-removebg-preview-1.png
    - assets/page-1/images/arrow-zW5.png
    - assets/page-1/images/tick-removebg-preview-5.png
    - assets/page-1/images/icon-5mb.png
    - assets/page-1/images/path-wXX.png
    - assets/page-1/images/group.png
    - assets/page-1/images/auto-group-c2xf.png
    - assets/page-1/images/oval.png
    - assets/page-1/images/icon-PvR.png
    - assets/page-1/images/ellipse-24.png
    - assets/page-1/images/percent-aLZ.png
    - assets/page-1/images/icon-2iM.png
    - assets/page-1/images/auto-group-eknq.png
    - assets/page-1/images/icon-RVs.png
    - assets/page-1/images/arrow-r1o.png
    - assets/page-1/images/icon-Sru.png
    - assets/page-1/images/auto-group-zfmw.png
    - assets/page-1/images/arrow-vzu.png
    - assets/page-1/images/base-L9P.png
    - assets/page-1/images/auto-group-daih.png
    - assets/page-1/images/auto-group-rnhj.png
    - assets/page-1/images/button-83B.png
    - assets/page-1/images/icon-fd3.png
    - assets/page-1/images/ellipse-24-7Kf.png
    - assets/page-1/images/icon-Z93.png
    - assets/page-1/images/qr-1.png
    - assets/page-1/images/auto-group-iwav.png
    - assets/page-1/images/item.png
    - assets/page-1/images/auto-group-yjps.png
    - assets/page-1/images/auto-group-znzz.png
    - assets/page-1/images/illustration.png
    - assets/page-1/images/more.png
    - assets/page-1/images/icon-6fj.png
    - assets/page-1/images/group-11.png
    - assets/page-1/images/auto-group-sqer.png
    - assets/page-1/images/item-Fa1.png
    - assets/page-1/images/illustration-NcR.png
    - assets/page-1/images/illustration-j5K.png
    - assets/page-1/images/auto-group-gw97.png
    - assets/page-1/images/auto-group-snwr.png
    - assets/page-1/images/icon-oDK.png
    - assets/page-1/images/path-uE9.png
    - assets/page-1/images/arrow-u4u.png
    - assets/page-1/images/arrow-V13.png
    - assets/page-1/images/more-KAR.png
    - assets/page-1/images/icon-gDF.png
    - assets/page-1/images/icon-isK.png
    - assets/page-1/images/icon-Yoj.png
    - assets/page-1/images/avatar-he1.png
    - assets/page-1/images/icon-GeV.png
    - assets/page-1/images/map.png
    - assets/page-1/images/icon-HL5.png
    - assets/page-1/images/flame.png
    - assets/page-1/images/icon-x25.png
    - assets/page-1/images/auto-group-qzcz.png
    - assets/page-1/images/auto-group-x6tp.png
    - assets/page-1/images/icon-S1f.png
    - assets/page-1/images/group-pTT.png
    - assets/page-1/images/auto-group-fccv.png
    - assets/page-1/images/group-FM3.png
    - assets/page-1/images/icon-jTF.png
    - assets/page-1/images/auto-group-iiwh.png
    - assets/page-1/images/ellipse-24-G4R.png
    - assets/page-1/images/icon-Uch.png
    - assets/page-1/images/auto-group-xeg5.png
    - assets/page-1/images/auto-group-8ruv.png
    - assets/page-1/images/icons-light-shoe-run.png
    - assets/page-1/images/auto-group-qfjm.png
    - assets/page-1/images/more-yxu.png
    - assets/page-1/images/close-8W5.png
    - assets/page-1/images/ellipse-25.png
    - assets/page-1/images/flame-VMj.png
    - assets/page-1/images/ellipse-24-tSm.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
